 export const ActionType = {
    ADD_DIGIT: 'ADD_DIGIT',
    CLEAR_DISPLAY: 'CLEAR_DISPLAY',
    PROCESS_BACKSPACE: 'PROCESS_BACKSPACE',
    CALC_PERCENTAGE: 'CALC_PERCENTAGE',
    TOGGLE_SIGN: 'TOGGLE_SIGN',
    ADD_DEC_SEPARATOR: 'ADD_DEC_SEPARATOR',
    ADD_OPERATOR: 'ADD_OPERATOR',
    TOGGLE_MENU: 'TOGGLE_MENU',
    CHANGE_THEME: 'CHANGE_THEME'
}